import { nanoid } from "nanoid";

import { CanvasDocument, CanvasElement, DEFAULT_PAGE } from "@/lib/editorTypes";

export type StarterTemplateCategory = "basic" | "logo" | "exam" | "minimal";

export type StarterTemplate = {
  id: string;
  name: string;
  description: string;
  category: StarterTemplateCategory;
  canvasJson: CanvasDocument;
};

function element(partial: Partial<CanvasElement> & Pick<CanvasElement, "type" | "name">): CanvasElement {
  return {
    id: nanoid(),
    x: 80,
    y: 80,
    width: 180,
    height: 48,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 0,
    fill: "#ffffff",
    stroke: "#111827",
    strokeWidth: 0,
    strokeStyle: "solid",
    color: "#111827",
    fontFamily: "NanumGothic",
    fontSize: 14,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 1.25,
    textAlign: "left",
    letterSpacing: 0,
    borderRadius: 0,
    ...partial,
  };
}

function doc(elements: CanvasElement[]): CanvasDocument {
  return {
    version: 1,
    page: { ...DEFAULT_PAGE },
    elements: elements.map((item, index) => ({ ...item, zIndex: index })),
    updatedAt: new Date().toISOString(),
  };
}

export const starterTemplates: StarterTemplate[] = [
  {
    id: "classic",
    name: "기본 시험지",
    description: "학원명, 시험 정보, 1단 문항 영역으로 구성된 가장 기본적인 시험지입니다.",
    category: "basic",
    canvasJson: doc([
      element({
        type: "dynamic_field",
        name: "학원명",
        fieldKey: "academy_name",
        previewValue: "Tena Academy",
        text: "{{학원명}}",
        x: 247,
        y: 42,
        width: 300,
        height: 34,
        fontSize: 18,
        fontWeight: "bold",
        textAlign: "center",
      }),
      element({
        type: "dynamic_field",
        name: "시험명",
        fieldKey: "exam_title",
        previewValue: "시험명: 중간고사 대비",
        text: "시험명: {{시험명}}",
        x: 80,
        y: 104,
        width: 330,
        height: 24,
        fontSize: 11,
      }),
      element({
        type: "dynamic_field",
        name: "이름",
        fieldKey: "student_name",
        previewValue: "이름: 홍길동",
        text: "이름: {{이름}}",
        x: 500,
        y: 104,
        width: 214,
        height: 24,
        fontSize: 11,
        textAlign: "right",
      }),
      element({
        type: "dynamic_field",
        name: "날짜",
        fieldKey: "date",
        previewValue: "날짜: 2026-05-07",
        text: "날짜: {{시험일자}}",
        x: 500,
        y: 132,
        width: 214,
        height: 24,
        fontSize: 11,
        textAlign: "right",
      }),
      element({
        type: "divider",
        name: "헤더 구분선",
        x: 80,
        y: 174,
        width: 634,
        height: 2,
        stroke: "#111827",
        strokeWidth: 1.5,
      }),
      element({
        type: "question_area",
        name: "문항 영역",
        x: 80,
        y: 206,
        width: 634,
        height: 820,
        fill: "transparent",
        stroke: "#d1d5db",
        strokeWidth: 1,
        columns: 1,
        questionNumberFormat: "문 {n}.",
        questionFontSize: 11,
        fontFamily: "NanumGothic",
      }),
      element({
        type: "dynamic_field",
        name: "페이지번호",
        fieldKey: "page_number",
        previewValue: "1",
        text: "{{페이지번호}}",
        x: 347,
        y: 1072,
        width: 100,
        height: 20,
        fontSize: 9,
        color: "#6b7280",
        textAlign: "center",
      }),
    ]),
  },
  {
    id: "logo",
    name: "로고형 시험지",
    description: "좌측에 업로드한 로고를 배치하기 좋은 여백과 우측 학원 정보, 2단 문항 배치가 있는 시험지입니다.",
    category: "logo",
    canvasJson: doc([
      element({
        type: "dynamic_field",
        name: "학원명",
        fieldKey: "academy_name",
        previewValue: "Tena Academy",
        text: "{{학원명}}",
        x: 492,
        y: 44,
        width: 222,
        height: 28,
        fontSize: 16,
        fontWeight: "bold",
        textAlign: "right",
      }),
      element({
        type: "dynamic_field",
        name: "시험명",
        fieldKey: "exam_title",
        previewValue: "파이널 모의고사",
        text: "{{시험명}}",
        x: 492,
        y: 76,
        width: 222,
        height: 20,
        fontSize: 10,
        color: "#334155",
        textAlign: "right",
      }),
      element({
        type: "dynamic_field",
        name: "반",
        fieldKey: "class_name",
        previewValue: "A반",
        text: "{{반}}",
        x: 492,
        y: 98,
        width: 222,
        height: 18,
        fontSize: 10,
        color: "#334155",
        textAlign: "right",
      }),
      element({
        type: "dynamic_field",
        name: "이름",
        fieldKey: "student_name",
        previewValue: "홍길동",
        text: "{{이름}}",
        x: 492,
        y: 120,
        width: 222,
        height: 18,
        fontSize: 10,
        color: "#334155",
        textAlign: "right",
      }),
      element({
        type: "dynamic_field",
        name: "날짜",
        fieldKey: "date",
        previewValue: "2026-05-07",
        text: "{{시험일자}}",
        x: 492,
        y: 142,
        width: 222,
        height: 18,
        fontSize: 10,
        color: "#334155",
        textAlign: "right",
      }),
      element({
        type: "divider",
        name: "상단 이중선 1",
        x: 80,
        y: 178,
        width: 634,
        height: 2,
        stroke: "#111827",
        strokeWidth: 2,
      }),
      element({
        type: "divider",
        name: "상단 이중선 2",
        x: 80,
        y: 186,
        width: 634,
        height: 1,
        stroke: "#111827",
        strokeWidth: 1,
      }),
      element({
        type: "question_area",
        name: "2단 문항 영역",
        x: 80,
        y: 216,
        width: 634,
        height: 810,
        fill: "transparent",
        stroke: "#e5e7eb",
        strokeWidth: 1,
        columns: 2,
        questionNumberFormat: "{n}.",
        questionFontSize: 10,
        fontFamily: "NanumGothic",
      }),
      element({
        type: "dynamic_field",
        name: "하단 학원명",
        fieldKey: "academy_name",
        previewValue: "Tena Academy",
        text: "{{학원명}}",
        x: 80,
        y: 1070,
        width: 240,
        height: 20,
        fontSize: 9,
        color: "#6b7280",
      }),
      element({
        type: "dynamic_field",
        name: "페이지번호",
        fieldKey: "page_number",
        previewValue: "1 / 1",
        text: "{{페이지번호}} / {{총페이지}}",
        x: 594,
        y: 1070,
        width: 120,
        height: 20,
        fontSize: 9,
        color: "#6b7280",
        textAlign: "right",
      }),
    ]),
  },
  {
    id: "exam",
    name: "모의고사형",
    description: "진한 헤더, 3분할 정보 바, 답안표 영역까지 포함한 모의고사 레이아웃입니다.",
    category: "exam",
    canvasJson: doc([
      element({
        type: "rect",
        name: "상단 헤더 바",
        x: 0,
        y: 0,
        width: 794,
        height: 132,
        fill: "#1a1a2e",
        strokeWidth: 0,
      }),
      element({
        type: "dynamic_field",
        name: "시험명",
        fieldKey: "exam_title",
        previewValue: "2026 실전 모의고사",
        text: "{{시험명}}",
        x: 120,
        y: 32,
        width: 554,
        height: 34,
        fontSize: 22,
        fontWeight: "bold",
        color: "#ffffff",
        textAlign: "center",
      }),
      element({
        type: "dynamic_field",
        name: "과목",
        fieldKey: "subject",
        previewValue: "수학",
        text: "과목: {{과목}}",
        x: 210,
        y: 82,
        width: 180,
        height: 24,
        fontSize: 12,
        color: "#ffffff",
        textAlign: "center",
      }),
      element({
        type: "dynamic_field",
        name: "학년",
        fieldKey: "class_name",
        previewValue: "고2",
        text: "학년: {{반}}",
        x: 404,
        y: 82,
        width: 180,
        height: 24,
        fontSize: 12,
        color: "#ffffff",
        textAlign: "center",
      }),
      element({
        type: "box",
        name: "정보 바",
        x: 80,
        y: 154,
        width: 634,
        height: 48,
        fill: "#ffffff",
        stroke: "#111827",
        strokeWidth: 1,
        borderRadius: 0,
      }),
      element({
        type: "rect",
        name: "정보 바 구분선 1",
        x: 291,
        y: 154,
        width: 1,
        height: 48,
        fill: "#111827",
        strokeWidth: 0,
      }),
      element({
        type: "rect",
        name: "정보 바 구분선 2",
        x: 502,
        y: 154,
        width: 1,
        height: 48,
        fill: "#111827",
        strokeWidth: 0,
      }),
      element({
        type: "dynamic_field",
        name: "반",
        fieldKey: "class_name",
        previewValue: "반: A반",
        text: "반: {{반}}",
        x: 96,
        y: 168,
        width: 178,
        height: 20,
        fontSize: 10,
        textAlign: "center",
      }),
      element({
        type: "dynamic_field",
        name: "이름",
        fieldKey: "student_name",
        previewValue: "이름: 홍길동",
        text: "이름: {{이름}}",
        x: 308,
        y: 168,
        width: 178,
        height: 20,
        fontSize: 10,
        textAlign: "center",
      }),
      element({
        type: "dynamic_field",
        name: "날짜",
        fieldKey: "date",
        previewValue: "날짜: 2026-05-07",
        text: "날짜: {{시험일자}}",
        x: 519,
        y: 168,
        width: 178,
        height: 20,
        fontSize: 10,
        textAlign: "center",
      }),
      element({
        type: "question_area",
        name: "2단 문항 영역",
        x: 80,
        y: 232,
        width: 634,
        height: 650,
        fill: "transparent",
        stroke: "#d1d5db",
        strokeWidth: 1,
        columns: 2,
        questionNumberFormat: "{n}.",
        questionFontSize: 10,
        fontFamily: "NanumGothic",
      }),
      element({
        type: "answer_table",
        name: "답안표 영역",
        x: 80,
        y: 914,
        width: 634,
        height: 112,
        fill: "#ffffff",
        stroke: "#111827",
        strokeWidth: 1,
        rows: 2,
        columns: 5,
        answersPerRow: 5,
        fontSize: 10,
      }),
      element({
        type: "dynamic_field",
        name: "페이지번호",
        fieldKey: "page_number",
        previewValue: "1",
        text: "{{페이지번호}}",
        x: 347,
        y: 1072,
        width: 100,
        height: 20,
        fontSize: 9,
        color: "#6b7280",
        textAlign: "center",
      }),
    ]),
  },
];

export function getStarterTemplate(id: string | null) {
  return starterTemplates.find((template) => template.id === id) || starterTemplates[0];
}
